---
title: "Simple Counts"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{simple-counts}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

getwd()
```

```{r setup}
library(rfars)
library(tidyverse)
library(leaflet)
# library(leaflet.extras)
```

```{r}
myFARS <- 
  get_fars(years = 2016:2020, states="Virginia") %>%
  use_fars()
```

```{r}
myFARS <-
  use_fars("C:/Users/s87ja/Dropbox/Work/toXcel/FARS/rfars/vignettes/FARS data/prepared/")
```


```{r}
myFARS %>%
  select(year, month, id) %>%
  unique() %>%
  group_by(year, month) %>%
  summarise(n=n(), .groups = "drop") %>%
  mutate(date = lubridate::make_date(year, match(month, month.name), 1)) %>%
  ggplot(aes(x=date, y=n)) +
  geom_col() +
  labs(title = "Monthly Fatal Crashes in Virginia")
```

```{r}
myFARS %>%
  select(year, month, rur_urb, id) %>%
  filter(rur_urb %in% c("Urban", "Rural")) %>%
  unique() %>%
  group_by(year, month, rur_urb) %>%
  summarise(n=n(), .groups = "drop") %>%
  mutate(date = lubridate::make_date(year, match(month, month.name), 1)) %>%
  ggplot(aes(x=date, y=n)) +
    geom_col() +
    facet_wrap(.~rur_urb, nrow = 1) +
    labs(title = "Monthly Fatal Crashes in Virginia by Rurality")
```

```{r}
myFARS %>%
  filter(rur_urb %in% c("Urban", "Rural"), inj_sev=="Fatal Injury (K)") %>%
  select(year, rur_urb, per_typ, id, veh_no, per_no) %>%
  unique() %>%
  group_by(year, rur_urb, per_typ) %>%
  summarise(n=n(), .groups = "drop") %>%
  filter(n>6) %>%
  ggplot(aes(x=year, y=n, fill=rur_urb)) +
    geom_col(position = "dodge") +
    facet_wrap(.~per_typ, nrow = 1, labeller = label_wrap_gen()) +
    labs(title = "Fatalities in Virginia by Rurality and Road User")
```

```{r}
myFARS %>%
  select(id, year, lat, lon) %>% unique() %>%
  leaflet() %>%
  addTiles() %>%
  addCircleMarkers(
    radius = 1,
    color = "red",
    stroke = FALSE,
    fillOpacity = 0.7, group = "Crash Locations") #%>%
  # addHeatmap(
  #   group = "Heatmap", 
  #   radius=10, 
  #   blur=20, 
  #   minOpacity = .6, max = 1, 
  #   cellSize = 10) %>%
  # addLayersControl(
  #   overlayGroups = c("Crash Locations", "Heatmap"),
  #   options = layersControlOptions(collapsed = FALSE))
```

